export const metadata = {
  title: 'Linkit',
  description: 'Generated by Linkit',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
