import {Inter , Poppins } from 'next/font/google'
import '../globals.css'
import Header from '@/components/Header'
import { getServerSession } from 'next-auth'
import { authOptions } from '../api/auth/[...nextauth]/route'
import Image from 'next/image'
import Sidebar from '@/components/layout/AppSidebar'
import { redirect } from 'next/navigation'



const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ['latin'],
})

const inter = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ['latin'],
})

export const metadata = {
  title: 'LinkIt',
  description: 'Generated by create next app',
}
export default async  function AppTemplate({ children , ...rest }) {
  const session = await getServerSession(authOptions);
  if(!session){
    return redirect('/')
  }
  
  return (
    <html lang="en">
      <body className={poppins.className }>
        <main >
          <Header/>
        <div className='flex h-screen  '>
          <div className='bg-primmary md:w-72 '>
            <aside className='border-t  border-secondry '> 
              <div className='flex items-center cursor-pointer p-4 gap-x-4 w-full truncate'>
                <Image src={session?.user?.image} width={40} height={40} alt={"avatar"} style={{borderRadius:"50px"}}/>
                <div>
                  <p className='text-secondry'>Hello,<span className='ml-1'>{session?.user?.name}</span></p>
                  <p className='text-xs text-secondry'>{session?.user?.email}</p>
                </div>
              </div>
             <Sidebar/>
            </aside>
          </div>
          <div className='grow'>
           <div className='max-w-4xl bg-secondry/20 w-full  p-4'>
              {children}
            </div>
          </div>
        </div>
        </main>
      </body>
    </html>
  )
}
