import {Inter , Poppins } from 'next/font/google'
import '../globals.css'
import Header from '@/components/Header'
import { getServerSession } from 'next-auth'
import { authOptions } from '../api/auth/[...nextauth]/route'
import Image from 'next/image'
import Sidebar from '@/components/layout/AppSidebar'

import { redirect } from 'next/navigation'
import { Toaster } from 'react-hot-toast'

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ['latin'],
})

export const metadata = {
  title: 'LinkIt',
  description: 'Generated by create next app',
}
export default async  function AppTemplate({ children , ...rest }) {
  const session = await getServerSession(authOptions);
  if(!session){
    return redirect('/')
  }
  
  console.log(session?.user?.image)
  return (
    <html lang="en">
      <body className={poppins.className }>
        <Toaster/>
        <main >
        <div className='flex h-screen  '>
          <div className='bg-normal-dark md:w-72 '>
            <aside className=' '> 
              <div className='flex items-center cursor-pointer p-4 gap-x-4 w-full truncate'>
               <div className='w-10 h-10  border-[#f7f6f6] border-2 rounded-full'>
                  <img className='h-full w-full rounded-full' src={session?.user?.image} alt="avatar"/>
               </div>
                <div>
                  <p className='text-white'>Hello,<span className='ml-1'>{session?.user?.name}</span></p>
                  <p className='text-xs text-white'>{session?.user?.email}</p>
                </div>
              </div>
             <Sidebar/>
            </aside>
          </div>
          <div className='grow flex items-center justify-center   '>
           <div className='max-w-4xl   w-full  p-4'>
              {children}
            </div>
          </div>
        </div>
        </main>
      </body>
    </html>
  )
}
