
import {Poppins} from 'next/font/google'
import '../../globals.css'

const poppins = Poppins({ subsets: ['latin'], weight: ['300' ,'400',  '500' , '700' , '800'] })

export const metadata = {
  title: 'Linkit/Userprofile',
  description: 'This is next app generated by Linkit',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={poppins.className} >
    <main>
        <div className="bg-normal-dark h-screen">{children}</div>
    </main>
    </body>
    </html>
  )
}