import { Poppins } from 'next/font/google'
import '../globals.css'



const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Linkit',
  description: 'Generated by create Linkit',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
